@base = https://localhost:7185
@fullName=user7185
@email=user7185@example.com
@password=P@ssw0rd

GET {{base}}/weatherforecast
Accept: application/json

###

POST {{base}}/register
Content-Type: application/json

{
  "fullName": "{{fullName}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

###

POST {{base}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

POST {{base}}/forgotPassword
Content-Type: application/json

{
  "email": "{{email}}"
}

###

@code=Q2ZESjhDd1NFUklZcUtCQ3MwWlF3MW9DbnptcnRZMW1wdmVsVTh4UmkrdFMyZ0tCelBZQkJKbFUvNUVyNktETlJQK1pjMWtZRGRQS3FTRDZHMmZTdis4TmJ0amtpcHBPckNuNkpRWVluZ2xVdEpLdmxUdGJ1UTJwKzJadm9iVjg5OEhUblBpZ1ZmUllUekRsRTZPRm5vNnU3SWk3cm5yV2tpSnp5dVE4ZGJBN1dydjEremVUelF6U0o0alNXMjljM0p5NmFGSGFQNHc1ZitLZlo0eE9lK2Z0bXcremx2QnJkNlpLenhFSjF5RnlBdkd6

POST {{base}}/resetPassword
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "{{code}}",
  "password": "{{password}}"
}

###

POST {{base}}/logout

###

POST {{base}}/claimBlog